In [13]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [21]:
with open("../data/raw/Superstore.csv", encoding="latin1") as f:
    lines = f.readlines()

for i in range(10, 20):  # mira líneas 10 a 20
    print(i+1, repr(lines[i]))

11 '10;CA-2014-115812;09/06/2014;14/06/2014;Standard Class;BH-11710;Brosina Hoffman;Consumer;United States;Los Angeles;California;90032;West;OFF-AP-10002892;Office Supplies;Appliances;Belkin F5C206VTEL 6 Outlet Surge;114,9;5;0;34,47\n'
12 '11;CA-2014-115812;09/06/2014;14/06/2014;Standard Class;BH-11710;Brosina Hoffman;Consumer;United States;Los Angeles;California;90032;West;FUR-TA-10001539;Furniture;Tables;Chromcraft Rectangular Conference Tables;1706,184;9;0,2;85,3092\n'
13 '12;CA-2014-115812;09/06/2014;14/06/2014;Standard Class;BH-11710;Brosina Hoffman;Consumer;United States;Los Angeles;California;90032;West;TEC-PH-10002033;Technology;Phones;Konftel 250 Conference\xa0phone\xa0- Charcoal black;911,424;4;0,2;68,3568\n'
14 '13;CA-2017-114412;15/04/2017;20/04/2017;Standard Class;AA-10480;Andrew Allen;Consumer;United States;Concord;North Carolina;28027;South;OFF-PA-10002365;Office Supplies;Paper;Xerox 1967;15,552;3;0,2;5,4432\n'
15 '14;CA-2016-161389;05/12/2016;10/12/2016;Standard Class;IM-15070;Irene Maddox;Consumer;United States;Seattle;Washington;98103;West;OFF-BI-10003656;Office Supplies;Binders;Fellowes PB200 Plastic Comb Binding Machine;407,976;3;0,2;132,5922\n'
16 '15;US-2015-118983;22/11/2015;26/11/2015;Standard Class;HP-14815;Harold Pawlan;Home Office;United States;Fort Worth;Texas;76106;Central;OFF-AP-10002311;Office Supplies;Appliances;Holmes Replacement Filter for HEPA Air Cleaner, Very Large Room, HEPA Filter;68,81;5;0,8;-123,858\n'
17 '16;US-2015-118983;22/11/2015;26/11/2015;Standard Class;HP-14815;Harold Pawlan;Home Office;United States;Fort Worth;Texas;76106;Central;OFF-BI-10000756;Office Supplies;Binders;Storex DuraTech Recycled Plastic Frosted Binders;2,544;3;0,8;-3,816\n'
18 '17;CA-2014-105893;11/11/2014;18/11/2014;Standard Class;PK-19075;Pete Kriz;Consumer;United States;Madison;Wisconsin;53711;Central;OFF-ST-10004186;Office Supplies;Storage;"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x 36""W x 18 1/2""D";665,88;6;0;13,3176\n'
19 '18;CA-2014-167164;13/05/2014;15/05/2014;Second Class;AG-10270;Alejandro Grove;Consumer;United States;West Jordan;Utah;84084;West;OFF-ST-10000107;Office Supplies;Storage;Fellowes Super Stor/Drawer;55,5;2;0;9,99\n'
20 '19;CA-2014-143336;27/08/2014;01/09/2014;Second Class;ZD-21925;Zuschuss Donatelli;Consumer;United States;San Francisco;California;94109;West;OFF-AR-10003056;Office Supplies;Art;Newell 341;8,56;2;0;2,4824\n'

In [23]:
df = pd.read_csv(
    "../data/raw/Superstore.csv",
    sep=";",
    encoding="latin1",
    engine="python"
)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,"261,96",2,0,"41,9136"
1,2,CA-2016-152156,08/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...","731,94",3,0,"219,582"
2,3,CA-2016-138688,12/06/2016,16/06/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,"14,62",2,0,"6,8714"
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,"957,5775",5,"0,45","-383,031"
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,"22,368",2,"0,2","2,5164"

In [24]:
df.shape
df.info()
df.describe()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   str
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   str
 20  Profit         9994 non-null   str
dtypes: int64(3), str(18)
memory usage: 1.6 MB

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [25]:
df.isnull().sum()
df.duplicated().sum()
df = df.drop_duplicates()

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    dayfirst=True
)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   str
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   str
 20  Profit         9994 non-null   str
dtypes: datetime64[us](2), int64(3), str(16)
memory usage: 1.6 MB

In [26]:
df["Month"] = df["Order Date"].dt.month_name()
df["Year"] = df["Order Date"].dt.year
df["Month Number"] = df["Order Date"].dt.month
df["Quarter"] = df["Order Date"].dt.quarter

In [27]:
# Convertir columnas numéricas
for col in ["Sales", "Profit", "Discount"]:
    df[col] = (
        df[col]
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

In [28]:
df[["Sales", "Profit", "Discount"]].dtypes

Sales       float64
Profit      float64
Discount    float64
dtype: object

In [29]:
df[["Sales", "Profit", "Discount"]].head(10)

      Sales    Profit  Discount
0  261.9600   41.9136      0.00
1  731.9400  219.5820      0.00
2   14.6200    6.8714      0.00
3  957.5775 -383.0310      0.45
4   22.3680    2.5164      0.20
5   48.8600   14.1694      0.00
6    7.2800    1.9656      0.00
7  907.1520   90.7152      0.20
8   18.5040    5.7825      0.20
9  114.9000   34.4700      0.00

In [30]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order ID"].nunique()
total_customers = df["Customer ID"].nunique()
total_products = df["Product ID"].nunique()

average_order = total_sales / total_orders

print(f"Total Sales: ${total_sales:,.2f}")
print(f"Total Profit: ${total_profit:,.2f}")
print(f"Orders: {total_orders}")
print(f"Customers: {total_customers}")
print(f"Products: {total_products}")
print(f"Average Order Value: ${average_order:,.2f}")

Total Sales: $2,297,200.86
Total Profit: $286,397.02
Orders: 5009
Customers: 793
Products: 1862
Average Order Value: $458.61

In [33]:
df.groupby("Category")["Sales"].sum().sort_values()
df.groupby("Category")["Profit"].sum().sort_values()

df.groupby("Product Name")["Sales"]\
    .sum()\
    .sort_values(ascending=False)\
    .head(10)

df.groupby("Customer Name")["Sales"]\
    .sum()\
    .sort_values(ascending=False)\
    .head(10)

df.groupby("Region")["Sales"].sum()

df.groupby("State")["Sales"]\
    .sum()\
    .sort_values(ascending=False)\
    .head(10)

df.groupby("State")["Profit"]\
    .sum()\
    .sort_values(ascending=False)\
    .head(10)

State
California    76381.3871
New York      74038.5486
Washington    33402.6517
Michigan      24463.1876
Virginia      18597.9504
Indiana       18382.9363
Georgia       16250.0433
Kentucky      11199.6966
Minnesota     10823.1874
Delaware       9977.3748
Name: Profit, dtype: float64

In [37]:
df.to_csv(
    "../data/processed/superstore_clean.csv",
    index=False
)